version: "3.8"
volumes:
  banco_local:
services:
  noticia:
    container_name: container_api_noticia
    build:
      dockerfile: Dockerfile.dev
      context: "."
    volumes:
      - .:/noticia
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    container_name: container_db
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5436:5432"