version: "3.8"
services:
  noticia:
    container_name: container_api_noticia
    build:
      dockerfile: Dockerfile.dev
      context: "."
    volumes:
      - .:/noticia
    ports:
      - "3000:3000"      
    environment:
      AWS_ACCESS_KEY_ID: AKIA3OJBPAZ4MAEPKGMP
      AWS_SECRET_ACCESS_KEY: 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
    depends_on:
      - postgres
  postgres:
    container_name: container_db
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5436:5432"