# syntax=docker/dockerfile:1
FROM ruby:2.7.4-bullseye
WORKDIR '/noticia'
COPY ./Gemfile .
COPY ./Gemfile.lock .

EXPOSE 3000

RUN gem install rails bundler
RUN bundle install

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]


# Configure the main process to run when running the image
CMD ["rails", "server", "-b", "0.0.0.0"]
